services:
  moonlight-web:
    image: mrcreativ3001/moonlight-web-stream:v2.10.0
    container_name: moonlight-web
    restart: unless-stopped
    network_mode: host
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - WEBRTC_NAT_1TO1_HOST=192.168.x.x
      - WEBRTC_PORT_RANGE=40000:40100
    volumes:
      - ./server:/moonlight-web/server
