services:
  caddy:
    build: .
    pull_policy: build
    image: caddy-duckdns:local
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
